### ISSUE TITLE
Feature: Validate bucket in taskcat config prior to launch

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#154]
From @avattathil 's comments in #151 

taskcat.yml specifies an s3bucket.
Example:

```
global:
  owner: owner@company.com
  qsname: sample-taskcat-project
  s3bucket: mytestbucket
```
s3bucket: mytestbucket <- Does not exist (it was deleted or never created)
In this case print a better message guiding the user (I can add it post merge)
