### ISSUE TITLE
Feature: Configurable CFN Stack Name

### ISSUE THREAD

**Issue by agamzn** [aws-quickstart/taskcat#171]
Currently the CFN Stack name is generated through a combination of command-line arguments and the `qsname` in the taskcat config. Certain resources have the `${AWS::StackName}` variable appended to the name to ensure no naming conflicts crop up. 

However, depending on the length of the CFN Stack Name, the total length of a resource name can exceed the maximum number of characters. 

Example Resource:

```
  PublicNLB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Type: network
      Name: !Sub
        - ${StackName}-nlb
        -
          StackName: !Ref AWS::StackName
      Scheme: internet-facing
      Subnets:
      - Ref: PublicSubnet1ID
      - Ref: PublicSubnet2ID
```

The [AWS Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-name) for the `AWS::ElasticLoadBalancingV2::LoadBalancer` resource type indicates the Name property cannot exceed 32 characters.

> Name
> 
>     Specifies a name for the load balancer. This name must be unique within your AWS account and can have a maximum of 32 alphanumeric characters and hyphens. A name can't begin or end with a hyphen. 

In this configuration, it's entirely possible the combination of `${StackName}-nlb` will exceed 32 characters. We need a way to customize the format of the generated CFN stack name. This should be within the config file, as the customization will be per-project.

Here's my proposed config:

```
global:
  owner: foobar@example.com
  qsname: quickstart-unicorn-spaceflight-solar-system
  stack_name_format: ${prefix},unicorn-space,${random_char_4}
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-unicorn-spaceflight-solar-system
    parameter_input: unicorn-spaceflight-solar-system.json
    template_file: unicorn-spaceflight-solar-system-master.template
```

Assuming a prefix of tcat-ci, the resulting stack name would be `tcat-ci-unicorn-space-AFGT`, with a length of 26. 

```
>>> len('tcat-ci-unicorn-space-AFGT')
26
```

The resulting resource name would have a length of 30.

```
>>> len('tcat-ci-unicorn-space-AFGT-nlb')
30

```
