### ISSUE TITLE
Proposal: embed ci config in cloudformation template

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/taskcat#222]
At present taskcat config must be stored in a separate file, typically located in `ci/taskcat.yaml` combined with at least one  parameter mapping file `ci/my-test.json` relative to the project root.

Supporting having this metadata in the template itself would have several benefits:

* Single file tests - any cfn template could be tested by taskcat without requiring any tool specific scaffolding. If metadata is not present taskcat just launches using defaults for stack parameters (potentially applying global overrides)
* Linting rules to extend `cfn-python-lint` can be created for taskcat configs and parameters within templates
* Cleaner, simpler setup for new users
* tools that generate quick start projects have to worry about less 
* simplify code base, there is a lot of scaffolding to deal with where to find the config file. This assumes that support for standalone config file is dropped, which may not happen for some time.

Potential concerns with this approach:

* how to define tests that involve multiple entrypoint templates would probably have to change. Scan folder structure for template files, any files with taskcat metadata get tested.
* backwards compatibility with standalone configs introduces additional maintenance burden

Proposed metadata structure:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  TaskCat::Config:
    MarketplaceAmi: false # Optional, defaults false
    Owner: quickstart@amazon.com # optional
    Name: quickstart-demo-redhat-openshift
    Regions: # optional, if not specified a single region is tested. Mutually exclusive to AllRegions
      - us-east-1
      - us-west-2
    AllRegions: true # reserved for future use, once taskcat can detect supported regions will launch tests in all regions supported by the resources in the template 
    Reporting: true # optional defaults true
    Tests: # optional, if not specified a single test will be launched, using all defaults
      MytemplateMytest:
        ParameterInput: myparams # optional, if not specified stack will be launched with defaults
        # template_file not needed, we'll launch the template this metadata is embedded in
        Regions:
          - us-west-2
    ParameterSets: # must be present if ParameterInput is specified in Tests
      myparams:
        KeyName: blah # Use shorthand instead of cfn ParameterKey, ParameterValue
        RemoteAccessCidr: 10.0.0.0/16
```

The presence of any metadata should not be required if taskcat is pointed to a particular template `taskcat ./templates/my-template.yaml` should launch 1 test in a predetermined default region (`us-east-2` ?) using all defaults for parameters. If taskcat is pointed at a project path `taskcat ./my-project/` then all templates found should be scanned for `TaskCat::Config` metatdata and if found tests defined should be run. A minimal config can be as little as:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  TaskCat::Config:
    Name: quickstart-demo-redhat-openshift
```

cc: @aws-quickstart/aws_quickstart_team
