### ISSUE TITLE
AMIUpdater: In-template filters assume region mapping exist

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#296]
AMIUpdater assumes that filters defined inside the template are in-use in the mappings section. This isn't always the case and a performance hit is encountered.  We need to add logic to account for this. 

Sample psuedo-cloudformation
```
Metadata:
  AWSAMIRegionMap:
    Filters:
      SLES12HVM:
        name: suse-sles-12-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP1HVM:
        name: suse-sles-12-sp1-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP1SAPBYOSHVM:
        name: suse-sles-sap-12-sp1-byos-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP2HVM:
        name: suse-sles-12-sp2-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP2SAPBYOSHVM:
        name: suse-sles-sap-12-sp2-byos-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP3HVM:
        name: suse-sles-12-sp3-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES12SP3SAPBYOSHVM:
        name: suse-sles-sap-12-sp3-byos-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES15SAPBYOSHVM:
        name: 'suse-sles-sap-15-byos-v????????-hvm-ssd-x86_64'
        owner-alias: amazon
      SLES15HVM:
        name: suse-sles-15-v????????-hvm-ssd-x86_64
        owner-alias: amazon
      SLES15HVMARM:
        name: suse-sles-15-v????????-hvm-ssd-arm64
        owner-alias: amazon
        architecture: arm64
      US1404HVM:
        name: ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-????????*
        owner-id: '099720109477'
      US1604HVM:
        name: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-????????*
        owner-id: '099720109477'
      US1604HVMARM:
        name: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-arm64-server-????????*
        owner-id: '099720109477'
        architecture: arm64
      US1804HVM:
        name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-????????*
        owner-id: '099720109477'
      US1804HVMARM:
        name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-????????*
        owner-id: '099720109477'
        architecture: arm64
Mappings:
  AWSAMIRegionMap:
    us-east-1:
      US1404HVM: ami-1
      US1604HVM: ami-2
      US1804HVM: ami-3
    us-east-2:
      US1404HVM: ami-4
      US1604HVM: ami-5
      US1804HVM: ami-6
```

In this example, even though the Ubuntu AMIs are mapped, the SUSE AMIs are queried.
