### ISSUE TITLE
Lint does not exclude the relevant checks, discarding configuration

### ISSUE THREAD

**Issue by drorasaf** [aws-quickstart/taskcat#325]
**Describe the bug**
When running with a config file .cfnlintrc, running the lint part of taskcat, it ignores the exclude flags

**To Reproduce**
1. Are you testing a *QuickStart* or *Custom template*? custom template
2. Attach or link a copy of the template if possible 
```
  ETLLambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code: "../functions/packages/etl/lambda.zip"
      Handler: "etl.lambda_handler"
      Runtime: "python3.6"
```
3. Provide the parameters that you passed.  
```
taskcat -c ci/taskcat.yaml 
```
which includes only one region(eu-west-1)
4. How did you install taskcat? 
pip3
5. Are you using a *profile*, *an instance role* or  *access keys* to run taskcat?
 access keys
6. Is your AWS environment configured via `aws configure`?
 yes
7. create a .cfnlintrc file in the folder with the following: 
```
ignore_checks:
- W3002
```
**Expected behavior**
I expect taskcat to load the relevant config, this `taskcat -c ci/taskcat.yaml -l` should return 0

**Version (Please make sure you are running the latest version of taskcat)
 - Taskcat Version (0.8.42), but I can see it in the latest master code
 - Python 3.6.8

**Additional context**
when I run cfn-lint on the same template file, the warning is being ignored.
I believe it's related to this line: https://github.com/aws-quickstart/taskcat/blob/master/taskcat/cfn_lint.py#L21
since get_rules does not load any config
