### ISSUE TITLE
How to Pass Parameters to CloudFormation

### ISSUE THREAD

**Issue by LackoDan** [aws-quickstart/taskcat#415]
I just started testing taskcat, and I cannot seem to figure out how to add parameters for CloudFormation to `.taskcat.yml`. 

It is not clear to me how to interpret this part in the documentstion: 
```
Parameter key-values to pass to CloudFormation, parameters provided in global config take precedence
<PARAMETER_NAME>
```

The README gives this example: 
```yaml
general:
  s3_bucket: my-globally-defined-bucket
  parameters:
    KeyPair: my-global-ec2-keypair
```

In the full `.taskcat.yml` example, there is something similar: 
```yaml
general:  # [OPTIONAL] General configuration settings.
  # [OPTIONAL] Parameter key-values to pass to CloudFormation, parameters provided in
  # global config take precedence
  parameters:
    MyParam: my-param-value
```

However, according to [this issue](https://github.com/aws-quickstart/taskcat/issues/267), it is not/was not possible to even use parameters in YAML files... 

I'm trying to add a commit hash as a parameter, like this: 
```yaml
project:
  name: my-project-name
  regions:
    - eu-central-1
tests:
  default:
    parameters:
      - CommitHash: 17e3d83
    template: ./my-project-template.yml
```

With taskcat version 0.9.7, that gives the following error: 
```
[ERROR  ] : ValidationError [{'CommitHash': '17e3d83'}] is not of type 'object'
```

I've also tried putting it into the project section, but that does not seem to make a difference. Could anyone please help me figure out what I'm doing wrong?

**Comment by andrew-glenn** [comment]
@LackoDan 

```
project:
  name: cfn-project
tests:
  mytest:
    template: templates/lab3.template.yaml
    regions:
    - us-east-1
    - us-east-2
    - us-west-1
    parameters:
      S3BucketName: '$[taskcat_autobucket]'
      S3KeyPrefix: 'cfn-project/'
      LicenseToken: 'MY-FAKE-LICENSE-KEY'
      AvailabilityZones: '$[taskcat_genaz_2]'
```

Should get you going. @ me if you run into trouble. 

-Andrew
