### ISSUE TITLE
taskcat 0.9.7 ParserError while parsing a flow sequence

### ISSUE THREAD

**Issue by shazi7804** [aws-quickstart/taskcat#420]
**Describe the bug**
taskcat run ParseError failed. 

**Expected behavior**
run `taskcat test run` but show error message.

- .taskcat.yml

```
general:
  s3_bucket: ba7ccb7276babebc4652e650937029a4dcd4f
project:
  owner: scott.liao@104.com.tw
  name: cfn-vpc-module
  regions:
    - ap-northeast-1
  parameters:
    VpcCIDR: 10.0.0.0/16
    PublicSubnetACIDR: 10.0.1.0/24
    PublicSubnetBCIDR: 10.0.2.0/24
    PrivateSubnet1ACIDR: 10.0.3.0/24
    PrivateSubnet1BCIDR: 10.0.4.0/24
    PrivateSubnet2ACIDR: 10.0.5.0/24
    PrivateSubnet2BCIDR: 10.0.6.0/24
    PrivateSubnet3ACIDR: 10.0.7.0/24
    PrivateSubnet3BCIDR: 10.0.8.0/24
tests:
  test-main-default:
    template: ./templates/main.yaml
    parameters:
      NameSuffix: tcat1
  test-main-vpc-logs:
    template: ./templates/main.yaml
    parameters:
      FlowLogEnable: true
      NameSuffix: tcat2
  test-main-endpoints:
    template: ./templates/main.yaml
    parameters:
      EndpointS3: true
      EndpointSQS: true
      NameSuffix: tcat3

```

- show messages.
```
[ERROR  ] : ParserError while parsing a flow sequence
  in "<unicode string>", line 993, column 13
did not find expected ',' or ']'
  in "<unicode string>", line 996, column 11
```

**Screenshots**
![image](https://user-images.githubusercontent.com/11752318/69120701-344d1480-0ad5-11ea-89b9-fd5f14260fe5.png)

**Version (Please make sure you are running the latest version of taskcat)
 - v0.9.7
