### ISSUE TITLE
TypeError 'NoneType' object is not iterable version 0.9.8

### ISSUE THREAD

**Issue by HienNguyenAsnet** [aws-quickstart/taskcat#433]
**Describe the bug**
I got an issue `TypeError 'NoneType' object is not iterable` with the latest version 0.9.8 on MacOS 10.14

**To Reproduce**
 - Install taskcat `pip3 install taskcat`
 - Write .taskcat.yml
```
general:
  s3_bucket: test-bucket
  auth:
    default: myaccount
project:
  name: my-cfn-project
  auth:
    default: myaccount
tests:
  default:
    auth:
      default: myaccount
    template: ./vpc.yml
    parameters:
      EnvironmentName: Test
```
 - Run `taskcat test run`. It's worked as expection
 - Add a nested stack to `vpc.yml` with wrong path
 - Run `taskcat test run`. I got `path not found` error and `TypeError 'NoneType' object is not iterable`
 - I replace wrong path with correct path (even s3 path). I don't got `path not found` any more but still got `TypeError 'NoneType' object is not iterable`
 - Now I got error `TypeError 'NoneType' object is not iterable` anytime run `taskcat test run`. I tried remove nested stack but the error still here.

**Screenshots**
![Screen Shot 2019-12-04 at 4 55 34 PM](https://user-images.githubusercontent.com/5277254/70132501-f6481700-16b6-11ea-8ae3-6e647d9202cd.png)
![Screen Shot 2019-12-04 at 4 58 17 PM](https://user-images.githubusercontent.com/5277254/70132685-49ba6500-16b7-11ea-9f3d-c29becc478f7.png)
![Screen Shot 2019-12-04 at 5 01 47 PM](https://user-images.githubusercontent.com/5277254/70132943-c9483400-16b7-11ea-92b8-74ae11419725.png)
![Screen Shot 2019-12-04 at 5 02 52 PM](https://user-images.githubusercontent.com/5277254/70133029-eda41080-16b7-11ea-8680-5ec7ffb46092.png)

**Version
 - Taskcat Version 0.9.8
 - Python 3.7.4
 - MacOS version 10.14
