### ISSUE TITLE
HOW TO use aws profile for taskcat 0.9.8

### ISSUE THREAD

**Issue by HienNguyenAsnet** [aws-quickstart/taskcat#434]
When I run `taskcat test run`, taskcat always uses default profile to access AWS System Manager. I can't set a profile for it with the newest version 0.9.8 and got error permission denied to access ssm if the default profile doesn't have permission for AWS System Manager. I am working with multiple accounts and profiles; I need to change the default profile access key and id. It's take a lot time. How to set a profile in this case?

.taskcat.yml
```
general:
  s3_bucket: test-bucket
  auth:
    default: myaccount
project:
  name: my-cfn-project
  auth:
    default: myaccount
tests:
  default:
    auth:
      default: myaccount
    template: ./ecs.yml
    parameters:
      EnvironmentName: Test
      VPCStackName: TestVPC
```

**Comment by andrew-glenn** [comment]
@HienNguyenAsnet  - it's not immediately clear what pain you're experiencing. However, you can set the default profile in the global config at ~/.taskcat.yml

```
general:
  auth:
    default: profile-for-everything
```

In your case where you need the test-specific profile to be something different, here's a sample config file.

```
project:
  name: my-cfn-project
tests:
  default:
    auth:
      default: profile-with-access-to-ssm
    template: ./ecs.yml
    parameters:
      EnvironmentName: Test
      VPCStackName: TestVPC
```

Please @ me if you have any further questions. Thanks!
