### ISSUE TITLE
Using `s3_enable_sig_v2: true` in `.taskcat.yml` is not working in version 0.9.8

### ISSUE THREAD

**Issue by russomi** [aws-quickstart/taskcat#445]
**Describe the bug**
Attempting to use `s3_enable_sig_v2: true` setting in `.taskcat.yml` with an auto-created bucket does not prevent [sigv4_policy](https://github.com/aws-quickstart/taskcat/blob/master/taskcat/_dataclasses.py#L176) from being applied to the bucket when running without the `--enable-sig-v2` cli argument.

**Workaround**
You can work around this issue by using `taskcat test run --enable-sig-v2`.

**To Reproduce**

1. Run `taskcat test run` with the following `.taskcat.yml`:

```yaml
project:
  name: qs-workshop
  owner: **redacted**
  s3_enable_sig_v2: true
  regions:
  - us-east-1
tests:
  lab-master-vpc:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      EmailAddress: **redacted**
      KeyPairName: taskcat-keypair
      QSS3BucketName: $[taskcat_autobucket]
      QSS3KeyPrefix: qs-workshop/
      RemoteAccessCIDR: 0.0.0.0/0
      WebserverCIDR: 0.0.0.0/0
    regions:
    - us-east-1
    template: templates/master.template.yaml
```

2. Confirm the auto-created bucket has the bucket policy that denies the use of sig_v2.

**Expected behavior**
Using `s3_enable_sig_v2: true` setting in `.taskcat.yml` should have the same behavior as `taskcat test run --enable-sig-v2`.

**Screenshots**
N/A

**Version**
 - Taskcat version 0.9.8
- Python 3.7.5

**Additional context**
- Installed via `pip`
- It appears that [this](https://github.com/aws-quickstart/taskcat/blob/master/taskcat/_cli_modules/test.py#L57) is overriding the `s3_enable_sig_v2: true` in `.taskcat.yml`?
