### ISSUE TITLE
Testing layered stacks

### ISSUE THREAD

**Issue by sampritavh** [aws-quickstart/taskcat#45]
Is there a way we can test stacks with layered architecture? Especially when there are dependencies between stacks? So for example if I have the configuration like below:
```
---
global:
  owner: example@flux7.com  
  qsname: test-shared-services
  regions:
    - us-east-1
    - us-west-2
  reporting: true
  tests:
    test-vpc:
      parameter_input: vpc-parameters.json
      regions:
      - us-east-1
      template_file: vpc/vpc.yaml
    test-app
      parameter_input: app-parameters.json
      regions:
      - us-east-1
      template_file: app/app.yaml
```
Here I have a template app.yaml which requires the vpc stack to be present.  So now if I  run taskcat with this configuration, what is ordering of task creation and deletion?
