### ISSUE TITLE
package_lambda: false is ignored

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#491]
**Describe the bug**
`package_lambda: false` has no effect. 


Sample taskcat config
```
project:
  name: sample-foobar
  owner: foobar@example.com
  regions:
    - us-east-1
  package_lambda: false
tests:
  f5-sca-security-stack:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      Foo: bar
      sshKey: placeholder
    template: templates/foo.template.json
```

Sample output

```
(...)
[INFO   ] : Packaging lambda source from <path/to/project>/lambda_functions/source/foo without building dependencies
```

**To Reproduce**
See above config.

**Expected behavior**
`package_lambda: false` is honored.

**Version (Please make sure you are running the latest version of taskcat)
```
❯ taskcat --version                                                                                                                                                                                                                                                                           10509   15:28:02
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|



version 0.9.13
0.9.13
```
