### ISSUE TITLE
PROPOSAL - per-test/per-region parameters

### ISSUE THREAD

**Issue by jaymccon** [aws-quickstart/taskcat#494]
At present parameters defined in the global config, used for overriding parameters defined in tests/projects, is a simple key-value representation of parameter names and values. where ever the name matches a parameter, it is overridden. This does not allow for providing per-test or per-region overrides. An example of this would be where a Quick Start requires a region specific ID as a parameter value. 

The proposed change has two components:

1. Allow nested parameters in `parameters` under `project` and `tests`. If the value of a key is a dict, and the key is a region name, then the parameters defined under it are only applied to that region. For example:

```
tests:
  some-test:
    parameters:
      eu-west-2:
        myParam: some-value-for-this-region
      myParam: default-value
```
This could alternatively be done by allowing sub-keys on the region lists instead of the parameters.

2. Create a new pseudo parameter that points to an override key. For example:

```
tests:
  some-test:
    parameters:
  myParam: $[override_myVal]
```
in the global config we would have `myVal` defined, and the value for that would be substituted.
```
general:
  parameters:
    myVal: this-value-will-go-to-myParam
```

with these two changes we would be able to do complex overrides, of potentially secret values:

```
project:
  parameters:
    myParam: $[override_defaultVal]
tests:
  some-test:
    parameters:
      eu-west-2:
        myParam: $[override_regionVal]
      myParam: $[override_testVal]
```

Thoughts ?

**Comment by jaymccon** [comment]
thinking about this a bit more, I prefer making 1. use the regions list. Provides slightly more flexibility, and means we don't need to deal with complicating the validation on parameter keys being either a literal key or a region name.

**Comment by andrew-glenn** [comment]
Is this a blocker, or nice-to-have?

**Comment by jaymccon** [comment]
It's a blocker to be able to run tests for connect integrations (they require a parameter with an id of an already existing connect instance in the same region). It's a nice to have for me because I have other use cases where it will simplify my life.

It's not a breaking change.

**Comment by andrew-glenn** [comment]
> It's not a breaking change.

Without additional logic, it is. Current test definitions expect..

```
parameters:
  key: value
```

Not

```
parameters:
  region_name:
    key:value
```

We'll need to add something like..

```
if isinstance(value, dict):
   (...)
elif isinstance(value, str):
   (...)
```

**Comment by jaymccon** [comment]
> since we assume key:value under parameters

parameters can be any type except dict at present (cfn doesn't accept dict). All this will introduce is that IF a parameter is of type dict, it is treated specially. At present taskcat will just crash if you give it a dict.

**Comment by andrew-glenn** [comment]
> > since we assume key:value under parameters
> 
> parameters can be any type except dict at present (cfn doesn't accept dict). All this will introduce is that IF a parameter is of type dict, it is treated specially. At present taskcat will just crash if you give it a dict.

More ☕️ needed. Happy to review a PR when it's ready.

**Comment by jaymccon** [comment]
I'm thinking it would be best to put the regional params under `regions` instead. This way we can do per region overrides for all tests (put it in `project`) or for a specific test (put it in `test`).

Example:

```
project:
  regions:
    - us-east-1:
        myParam: ue1val
    - ca-central-1
tests:
  basic-test:
    parameters:
      myParam: basic-test-default
  override-test:
    regions:
      - us-west-2:
          myParam: override-test-uw2val
      - us-east-1:
          myParam: override-test-ue1val
      - ca-central-1
  parameters:
    myParam: override-test-default
```
would result in the following stacks/parameters:

basic-test - us-east-1 - myParam: ue1val
basic-test - ca-central-1 - myParam: basic-test-default
override-test - us-west-2 - myParam: override-test-uw2val
override-test - us-east-1 - myParam: override-test-ue1val
override-test - ca-central-1 - myParam: basic-test-default

@avattathil @andrew-glenn thoughts ?
