### ISSUE TITLE
Public Read write access to the buckets where resources are uploaded. 

### ISSUE THREAD

**Issue by pankajvkulkarni** [aws-quickstart/taskcat#52]
Hi, 

I see that the buckets which are getting created as got public-read 

1. https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L317
2. https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L325

Also the objects which are being uploaded to the bucket has got public-read permission 

https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L349

Is it necessary to have the "public-read" for the buckets and the objects ?

**Comment by avattathil** [comment]
It depends on how the cfn is structured. If your userdata is using curl to pull file then yes public read is needed.
You can also add a existing private bucket and IAM roles to your cfn. 
If the `s3bucket` is specified in the _config.yml_ then taskcat will not create a bucket. 
```
global:
  owner: owner@company.com
  project: sample-cloudformation-project <- Must match the root directory of project (usually the name of git repo)
  s3bucket: projectx-templates
```
