### ISSUE TITLE
Cannot find directory (when run inside the project)

### ISSUE THREAD

**Issue by chrisduong** [aws-quickstart/taskcat#53]
Hi,

I'm using Taskcat version **2017.908.112800** on MacOS.

My project is:

- Path: /Users/abc/sample-taskcat-project
- Subfolders:

```
.
├── ci
│   ├── config.yml
│   ├── debug-input.json
│   ├── taskcat-autobucket.yml
│   └── taskcat.yml
├── scripts
│   └── scripts_userdata.sh
└── templates
    ├── debug-yaml.template
    └── debug.template

```
- Config.yml:
```
global:
  owner: abc@abc.com
  qsname: sample-taskcat-project
  regions:
    - ap-southeast-1

  reporting: true
tests:
  taskcat-test1:
    parameter_input: debug-input.json
    regions:
      - ap-southeast-1
    template_file: debug.template
``

The When I ran `taskcat -c ci/config.yml`. I got this error.

```
[taskcat] :Reading Config form: ci/config.yml
[taskcat] |Queing test => taskcat-test1 
[INFO   ] :Creating bucket taskcat-sample-taskcat-project-f3cab85a in us-east-1
[INFO   ] :Staging Bucket => [taskcat-sample-taskcat-project-f3cab85a]
		 Hint: The name specfied as value of qsname (sample-taskcat-project)
                    must match the root directory of your project
[ERROR  ] :!Cannot find directory [sample-taskcat-project] in /Users/cduong13/GDrive/Workspace/sample-taskcat-project
[INFO   ] :Please cd to where you project is located
```

Another confusion is, in README, you say the `config.yml` file use the key `project` for the PROJECT NAME but in the example (the `taskcat.yml` use `qsname` key).
After the above error, I tried to use `project`, it would complain that **global: qsname missing from ci/config.yml**.

Best,
