### ISSUE TITLE
Taskcat fails if template is in parent directory

### ISSUE THREAD

**Issue by darkn3rd** [aws-quickstart/taskcat#545]
### Description

The template cannot exist in parent directory and cannot be a symlink.

I would like to have my test scripts and related content in a `tests` directory.

### STEPS

Either a symlink or referencing a the parent directory fail.

#### SCENARIO 1

```yaml
project:
  name: my_project
  regions:
   - us-west-1
  - us-west-2
tests:
  default:
    parameters:
      KeyName: my_key
    template: ../my_template.json
```

```bash
taskcat test run
```

#### SCENARIO 2

```yaml
project:
  name: my_project
  regions:
   - us-west-1
  - us-west-2
tests:
  default:
    parameters:
      KeyName: my_key
    template: ./my_template.json
```

```bash
ln -s ../my_template.json my_template.json
taskcat test run
```

#### INSTALL STEPS

AWS profile used, working.

```bash
brew install pyenv 
brew install pyenv-virtualenv
pyenv install 3.8.0
echo 'aws' > .python-version 
pyenv virtualenv 3.8.0 aws
cd .
pip install taskcat
pip install awscli
```

### ACTUAL BEHAVIOR

```
[ERROR  ] : ValueError '/Users/joaquin/projects/aws/my_template.json' does not start with '/Users/joaquin/projects/aws/tests'
```

### EXPECTED BEHAVIOR

This would work with relative path `../my.template.json` or a symlink to that template, and reference it locally `./my.template.json`

### VERSIONS

* TaskCat `0.9.17`
