### ISSUE TITLE
Linter fails for true false values in CF config

### ISSUE THREAD

**Issue by Led1-ch** [aws-quickstart/taskcat#580]
Below is part of a config that works perfectly fine in cloudformation via the aws console.
```
  ExampleStudies:

    Type: String

    Description: "Include example studies in Atlas?"

    AllowedValues:

      - "true"

      - "false"

    Default: true 
```

However I get the linter error `[2015] [Default value is within parameter constraints] Default should be a value within AllowedValues` which is fixed by removing the quotation marks. I am pulling this template from an s3 bucket and am not in charge of the template and this seems like a case where it should give a warning instead.
