### ISSUE TITLE
Package subcommand appears to not implicitly honor config file settings

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#595]
Config file snipplet.

```
project:
  name: foobar
  owner: blah@example.com
  regions:
    - us-east-2
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambda: true
  s3_regional_buckets: true
```

When running `taskcat package`, I need to explicitly pass the options to define the source and zip directories.

```
❯ taskcat package -p .
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|



version 0.9.19
❯
```
When explicitly passing args.

```
❯ taskcat package -p . -s functions/source -z functions/packages
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|



version 0.9.19
[INFO   ] : Packaging lambda source from <redacted> without building dependencies
```
