### ISSUE TITLE
Parameter CreateVPNEndpoint failed to satisfy constraint: Must specify 'true' or 'false'

### ISSUE THREAD

**Issue by rezabekf** [aws-quickstart/taskcat#627]
**Describe the bug**
Issue reading in default value set within the allowed values.

Template:
```
Parameters:
  CreateVPNEndpoint:
    Type: String
    AllowedValues:
      - false
      - true
    Default: false
    ConstraintDescription: Must specify 'true' or 'false'
```
Taskcat Config:
```
project:
  lambda_source_path: ./src
  package_lambda: true
  regions:
    - us-east-1
tests:
  default:
    parameters:
      StackName: taskcat-aws-dcc-win
      AvailabilityZones: $[taskcat_genaz_2]
      DomainAdminPassword: $[taskcat_genpass_8A]
    regions:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - ap-south-1
      - ap-northeast-1
      - ap-southeast-2
      - ap-southeast-1
      - ap-northeast-2
    template: ./cfn/packaged.template
```

**Expected behavior**
Accept default value

**Debug**
```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Parameter CreateVPNEndpoint failed to satisfy constraint: Must specify 'true' or 'false'
```

 - Taskcat Version: 0.9.20
 - Python Version: Python 3.9.0

**Comment by andrew-glenn** [comment]
We've run into this ourselves. This is a CloudFormation generated issue. Something service-side changed in 2020. Previously, the service would interpret your Allowed Values as a list of strings. 

However, explicit typing seems to be enforced at this point. When specifying a `String` for  a parameter type, the list of Allowed Values also need to be strings. Your example has them as booleans.

This modification to your example should result in success.

```
Parameters:
  CreateVPNEndpoint:
    Type: String
    AllowedValues:
      - 'false'
      - 'true'
    Default: 'false'
    ConstraintDescription: Must specify 'true' or 'false'
```

I was under the impression that `cfn-lint` (the underlying linting engine for taskcat) would catch this. I seem to be mistaken.
