### ISSUE TITLE
[Feature] Multi-partition support for AMIUpdater (update-ami)

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/taskcat#666]
The current `taskcat update-ami` config format is not partition aware. The proposal is to revamp the config to be partition-aware.

Current:

```
RHELHA83HVM:
  name: RHEL_HA-8.3_HVM-????????-x86_64-?-Hourly2-GP2
  owner-id: '309956199498'
```

Proposed:

```
RHELHA83HVM:
  name: RHEL_HA-8.3_HVM-????????-x86_64-?-Hourly2-GP2
  partition:
    aws: 
      owner-id: '309956199498'
    aws-cn:
      owner-id: '0123456789012'
    aws-us-gov:
      owner-id: '0123456789013'
```

If `owner-id` found in `<mapping>.keys()`, the default partition is `aws`, for backwards compatibility.

/cc @davdunc for commentary, as his use-case/team buy-in is critical
