### ISSUE TITLE
Can I override the Taskcat stack prefix to a value other than "tCat"

### ISSUE THREAD

**Issue by lachlan-vass** [aws-quickstart/taskcat#671]
My organization uses naming policies to enforce stack names. They must start with a given prefix.

However Taskcat stacks always seem to begin with "tCat", and I cannot see a configuration option that will allow that to change. 

Is there an option I am not aware of? 

If not, can we implement a parameter to change the prefix of the taskcat stack name?

**Comment by lachlan-vass** [comment]
I can see references in `taskcat/_dataclasses.py` for a parameter called ` "stack_name_prefix": {"description": "Prefix to apply to generated CFN Stack Name"},`  as being related to TestConfig's. 

Also a refence to `stack_name_prefix` in `taskcat/cfg/config_schema.json` However I cannot see any documentation on how to apply this value. 

When I attempt to use it in a test I get `: ValidationError Additional properties are not allowed ('stack_name_prefix' was unexpected)` 

For example: 

```
tests:
  # S3 Bucket 
  s3BucketWillDeploy:
    parameters:
      BucketName: org-prefix-service-catalog-bucket-1
    regions:
    - ap-southeast-2
    template: products/s3/s3-bucket.template-v.1.0.2.json
    stack_name_prefix: "org-prefix"
```

... will generate the above `ValidationError`
