### ISSUE TITLE
Providing AWS::StackId value

### ISSUE THREAD

**Issue by namedgraph** [aws-quickstart/taskcat#679]
**Describe the bug**
`cdk deploy` succeeds but ` taskcat test run` fails:
```
[ERROR  ] : ClientError An error occurred (ValidationError) when calling the CreateStack operation: Template error: Fn::Select  cannot select nonexistent value at index 1
```

**To Reproduce**
Custom template which uses `Fn::Select` in this single place:
```
  LinkedDataHubLogGroup9D1FA54B:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - /ecs/linkeddatahub-
            - Fn::Select:
                - 1
                - Fn::Split:
                    - :stack/LinkedDataHubStack/
                    - Ref: AWS::StackId
```

**Expected behavior**
I was expecting the test to succeed, but my guess is it fails due to the missing `AWS::StackId` value. I was looking at the documentation for ways to provide it, but was unable to find. Tried to specify it under `parameters` but that didn't work.

**Version**

taskcat 0.9.23.
